// All copy for the support center, in the three languages the app ships with
// (Turkish default, English, Russian). Contact details mirror the Antalya
// restaurant; update the CONTACT block in one place if they change.

export const CONTACT = {
  whatsapp: '+90 555 000 0000',
  phone: '+90 242 000 0000',
  email: 'destek@sushitime.com',
  telegram: '@sushitime',
  address: 'Antalya, Türkiye',
};

export const LANGS = ['tr', 'en', 'ru'];

export const UI = {
  tr: {
    brandSub: 'Yardım Merkezi',
    eyebrow: '7/24 Destek',
    heroTitle: 'Size nasıl yardımcı olabiliriz?',
    heroSub: 'Sipariş, teslimat ve ödeme hakkında her şey. Aşağıdan arayın ya da bize yazın.',
    searchPlaceholder: 'Bir soru arayın… örn. "teslimat süresi"',
    contactTitle: 'Bize ulaşın',
    contactSub: 'En hızlı yanıt için WhatsApp’tan yazın.',
    cWhatsApp: 'WhatsApp', cWhatsAppHint: 'Anında yanıt',
    cPhone: 'Telefon', cPhoneHint: 'Her gün 10:00–23:00',
    cEmail: 'E-posta', cEmailHint: '24 saat içinde',
    cTelegram: 'Telegram', cTelegramHint: 'Kanal & destek',
    faqTitle: 'Sık sorulan sorular',
    faqSub: 'En çok merak edilenleri derledik.',
    catAll: 'Tümü', catOrders: 'Siparişler', catDelivery: 'Teslimat', catPayment: 'Ödeme', catAccount: 'Hesap',
    noResults: 'Aramanızla eşleşen sonuç yok. Bize doğrudan yazabilirsiniz.',
    infoHours: 'Çalışma saatleri', infoHoursVal: 'Her gün 10:00 – 23:00',
    infoArea: 'Teslimat bölgesi', infoAreaVal: 'Antalya geneli',
    infoFree: 'Ücretsiz teslimat', infoFreeVal: '25 ₺ üzeri siparişlerde',
    ctaTitle: 'Cevabı bulamadınız mı?',
    ctaSub: 'Destek ekibimiz size yardımcı olmaktan mutluluk duyar.',
    ctaBtn: 'WhatsApp’tan yazın',
    footerRights: 'Tüm hakları saklıdır.',
    fOrder: 'Sipariş ver', fMenu: 'Menü', fPrivacy: 'Gizlilik',
  },
  en: {
    brandSub: 'Help Center',
    eyebrow: '24/7 Support',
    heroTitle: 'How can we help you?',
    heroSub: 'Everything about orders, delivery and payment. Search below or message us.',
    searchPlaceholder: 'Search a question… e.g. "delivery time"',
    contactTitle: 'Get in touch',
    contactSub: 'WhatsApp is the fastest way to reach us.',
    cWhatsApp: 'WhatsApp', cWhatsAppHint: 'Instant reply',
    cPhone: 'Phone', cPhoneHint: 'Daily 10:00–23:00',
    cEmail: 'Email', cEmailHint: 'Within 24 hours',
    cTelegram: 'Telegram', cTelegramHint: 'Channel & support',
    faqTitle: 'Frequently asked questions',
    faqSub: 'The things people ask us most.',
    catAll: 'All', catOrders: 'Orders', catDelivery: 'Delivery', catPayment: 'Payment', catAccount: 'Account',
    noResults: 'No results match your search. Feel free to message us directly.',
    infoHours: 'Opening hours', infoHoursVal: 'Daily 10:00 – 23:00',
    infoArea: 'Delivery area', infoAreaVal: 'All of Antalya',
    infoFree: 'Free delivery', infoFreeVal: 'On orders over 25 ₺',
    ctaTitle: 'Still can’t find an answer?',
    ctaSub: 'Our support team is happy to help you out.',
    ctaBtn: 'Message us on WhatsApp',
    footerRights: 'All rights reserved.',
    fOrder: 'Order now', fMenu: 'Menu', fPrivacy: 'Privacy',
  },
  ru: {
    brandSub: 'Центр поддержки',
    eyebrow: 'Поддержка 24/7',
    heroTitle: 'Чем мы можем помочь?',
    heroSub: 'Всё о заказах, доставке и оплате. Поищите ниже или напишите нам.',
    searchPlaceholder: 'Поиск вопроса… напр. «время доставки»',
    contactTitle: 'Связаться с нами',
    contactSub: 'Быстрее всего ответим в WhatsApp.',
    cWhatsApp: 'WhatsApp', cWhatsAppHint: 'Мгновенный ответ',
    cPhone: 'Телефон', cPhoneHint: 'Ежедневно 10:00–23:00',
    cEmail: 'Эл. почта', cEmailHint: 'В течение 24 часов',
    cTelegram: 'Telegram', cTelegramHint: 'Канал и поддержка',
    faqTitle: 'Частые вопросы',
    faqSub: 'То, что спрашивают чаще всего.',
    catAll: 'Все', catOrders: 'Заказы', catDelivery: 'Доставка', catPayment: 'Оплата', catAccount: 'Аккаунт',
    noResults: 'Ничего не найдено. Напишите нам напрямую — поможем.',
    infoHours: 'Часы работы', infoHoursVal: 'Ежедневно 10:00 – 23:00',
    infoArea: 'Зона доставки', infoAreaVal: 'Вся Анталья',
    infoFree: 'Бесплатная доставка', infoFreeVal: 'При заказе от 25 ₺',
    ctaTitle: 'Не нашли ответ?',
    ctaSub: 'Наша команда поддержки рада помочь.',
    ctaBtn: 'Написать в WhatsApp',
    footerRights: 'Все права защищены.',
    fOrder: 'Заказать', fMenu: 'Меню', fPrivacy: 'Конфиденциальность',
  },
};

// category keys: orders | delivery | payment | account
export const FAQ = [
  {
    cat: 'orders',
    tr: { q: 'Nasıl sipariş verebilirim?', a: 'Menüden ürünleri sepete ekleyin, teslimat adresinizi girin ve ödeme yöntemini seçip siparişi onaylayın. Birkaç dakikada hazır!' },
    en: { q: 'How do I place an order?', a: 'Add items to your cart from the menu, enter your delivery address, pick a payment method and confirm. It only takes a minute!' },
    ru: { q: 'Как сделать заказ?', a: 'Добавьте блюда в корзину из меню, укажите адрес доставки, выберите способ оплаты и подтвердите заказ. Это займёт пару минут!' },
  },
  {
    cat: 'orders',
    tr: { q: 'Siparişimi takip edebilir miyim?', a: 'Evet. “Siparişler” bölümünden siparişinizin durumunu (hazırlanıyor, yolda, teslim edildi) gerçek zamanlı izleyebilirsiniz.' },
    en: { q: 'Can I track my order?', a: 'Yes. From the “Orders” section you can follow your order status (preparing, on the way, delivered) in real time.' },
    ru: { q: 'Могу ли я отследить заказ?', a: 'Да. В разделе «Заказы» вы видите статус заказа (готовится, в пути, доставлен) в реальном времени.' },
  },
  {
    cat: 'orders',
    tr: { q: 'Siparişimi iptal edebilir miyim?', a: 'Sipariş hazırlanmaya başlamadan önce iptal edilebilir. Lütfen en kısa sürede WhatsApp veya telefon üzerinden bize ulaşın.' },
    en: { q: 'Can I cancel my order?', a: 'Orders can be cancelled before preparation starts. Please contact us via WhatsApp or phone as soon as possible.' },
    ru: { q: 'Можно ли отменить заказ?', a: 'Заказ можно отменить до начала приготовления. Свяжитесь с нами в WhatsApp или по телефону как можно скорее.' },
  },
  {
    cat: 'delivery',
    tr: { q: 'Teslimat ne kadar sürer?', a: 'Ortalama teslimat süremiz 30 dakikadır. Yoğun saatlerde ve hava koşullarına göre süre değişebilir.' },
    en: { q: 'How long does delivery take?', a: 'Our average delivery time is 30 minutes. It may vary during peak hours or bad weather.' },
    ru: { q: 'Сколько занимает доставка?', a: 'В среднем доставка занимает 30 минут. В часы пик и при плохой погоде время может меняться.' },
  },
  {
    cat: 'delivery',
    tr: { q: 'Hangi bölgelere teslimat yapıyorsunuz?', a: 'Antalya genelinde teslimat yapıyoruz. Adresiniz teslimat bölgemizin dışındaysa ödeme adımında bilgilendirilirsiniz.' },
    en: { q: 'Which areas do you deliver to?', a: 'We deliver across Antalya. If your address falls outside our delivery zone, you’ll be notified at checkout.' },
    ru: { q: 'В какие районы вы доставляете?', a: 'Мы доставляем по всей Анталье. Если адрес вне зоны доставки, вы увидите уведомление при оформлении.' },
  },
  {
    cat: 'delivery',
    tr: { q: 'Teslimat ücreti ne kadar?', a: '25 ₺ ve üzeri siparişlerde teslimat ücretsizdir. Daha düşük tutarlarda sabit bir teslimat ücreti uygulanır.' },
    en: { q: 'How much is delivery?', a: 'Delivery is free on orders of 25 ₺ and above. A small flat fee applies to smaller orders.' },
    ru: { q: 'Сколько стоит доставка?', a: 'Доставка бесплатна при заказе от 25 ₺. Для меньших сумм действует небольшая фиксированная плата.' },
  },
  {
    cat: 'payment',
    tr: { q: 'Hangi ödeme yöntemlerini kabul ediyorsunuz?', a: 'Kapıda nakit ve kapıda kart ile ödeme kabul ediyoruz. Ödeme yöntemini sipariş sırasında seçebilirsiniz.' },
    en: { q: 'Which payment methods do you accept?', a: 'We accept cash on delivery and card on delivery. You can choose your method during checkout.' },
    ru: { q: 'Какие способы оплаты вы принимаете?', a: 'Принимаем оплату наличными и картой при получении. Способ выбирается при оформлении заказа.' },
  },
  {
    cat: 'payment',
    tr: { q: 'Promosyon kodu nasıl kullanılır?', a: 'Ödeme ekranındaki “Promosyon Kodu” alanına kodu girip “Uygula”ya basın. İndirim toplam tutara anında yansır.' },
    en: { q: 'How do I use a promo code?', a: 'Enter the code in the “Promo Code” field on the checkout screen and tap “Apply”. The discount is applied to your total instantly.' },
    ru: { q: 'Как использовать промокод?', a: 'Введите код в поле «Промокод» на экране оформления и нажмите «Применить». Скидка применится к сумме сразу.' },
  },
  {
    cat: 'account',
    tr: { q: 'Hesap oluşturmadan sipariş verebilir miyim?', a: 'Evet, misafir olarak sipariş verebilirsiniz. Ancak hesap açarsanız sipariş geçmişinizi ve adreslerinizi saklayabilirsiniz.' },
    en: { q: 'Can I order without an account?', a: 'Yes, you can order as a guest. Creating an account lets you save your order history and addresses.' },
    ru: { q: 'Можно ли заказать без аккаунта?', a: 'Да, можно оформить заказ как гость. С аккаунтом вы сохраните историю заказов и адреса.' },
  },
  {
    cat: 'account',
    tr: { q: 'Şifremi unuttum, ne yapmalıyım?', a: 'Giriş ekranından destek ekibimizle iletişime geçin; hesabınızı doğruladıktan sonra şifrenizi sıfırlamanıza yardımcı oluruz.' },
    en: { q: 'I forgot my password, what now?', a: 'Reach our support team from the login screen; once we verify your account we’ll help you reset your password.' },
    ru: { q: 'Я забыл пароль, что делать?', a: 'Свяжитесь с поддержкой с экрана входа; после проверки аккаунта мы поможем сбросить пароль.' },
  },
];
